<?php
/**
 * Plugin Name:       SVG Enabler
 * Plugin URI:        https://github.com/optimisthub/wordpress-svg-enabler
 * Description:       Safely enable SVG uploads in WordPress. Every uploaded SVG is sanitized to strip scripts, event handlers and remote references before it reaches your media library.
 * Version:           2.0.0
 * Requires at least: 6.0
 * Tested up to:      7.1
 * Requires PHP:      7.4
 * Author:            Optimist Hub
 * Author URI:        https://optimisthub.com
 * License:           GPL-2.0-or-later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       svg-enabler
 * Domain Path:       /languages
 *
 * @package OptimistHub\SvgEnabler
 */

declare( strict_types = 1 );

namespace OptimistHub\SvgEnabler;

defined( 'ABSPATH' ) || exit;

define( 'SVG_ENABLER_VERSION', '2.0.0' );
define( 'SVG_ENABLER_FILE', __FILE__ );
define( 'SVG_ENABLER_DIR', plugin_dir_path( __FILE__ ) );

/**
 * Composer autoloader.
 *
 * The plugin ships a PSR-4 autoloader generated by Composer. If it is missing
 * (for example when the plugin is installed from a source checkout rather than
 * a release archive) we register a small fallback so the plugin still works.
 */
if ( is_readable( SVG_ENABLER_DIR . 'vendor/autoload.php' ) ) {
	require_once SVG_ENABLER_DIR . 'vendor/autoload.php';
} else {
	spl_autoload_register(
		static function ( $class ) {
			$prefix = __NAMESPACE__ . '\\';

			if ( 0 !== strpos( $class, $prefix ) ) {
				return;
			}

			$relative = substr( $class, strlen( $prefix ) );
			$path     = SVG_ENABLER_DIR . 'src/' . str_replace( '\\', '/', $relative ) . '.php';

			if ( is_readable( $path ) ) {
				require_once $path;
			}
		}
	);
}

/**
 * Bail early with an admin notice when the environment cannot support the plugin.
 *
 * SVG sanitization relies on ext-dom and ext-libxml. Without them we must not
 * enable SVG uploads at all, because unsanitized SVG is a stored-XSS vector.
 */
if ( ! class_exists( \DOMDocument::class ) ) {
	add_action(
		'admin_notices',
		static function () {
			if ( ! current_user_can( 'activate_plugins' ) ) {
				return;
			}

			printf(
				'<div class="notice notice-error"><p>%s</p></div>',
				esc_html__(
					'SVG Enabler requires the PHP "dom" and "libxml" extensions. SVG uploads stay disabled until they are enabled.',
					'svg-enabler'
				)
			);
		}
	);

	return;
}

require_once SVG_ENABLER_DIR . 'src/Plugin.php';

/**
 * Boot the plugin.
 *
 * @return Plugin
 */
function plugin() {
	static $instance = null;

	if ( null === $instance ) {
		$instance = new Plugin();
		$instance->boot();
	}

	return $instance;
}

plugin();
